#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'doubleInvertedPendulum','console_scripts','dynamics_sim'
__requires__ = 'doubleInvertedPendulum'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('doubleInvertedPendulum', 'console_scripts', 'dynamics_sim')()
    )
